forms/admin_login.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, PasswordField
from wtforms.validators import DataRequired


class AdminForm(FlaskForm):

    username = StringField("Username",
                           validators=[DataRequired()],
                           render_kw={"placeholder": "Your Username.."}
                           )
    password = PasswordField("Password",
                             validators=[DataRequired()],
                             render_kw={"placeholder": "**********"}
                             )
    submit = SubmitField("Send")

forms/project_form.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField
from flask_ckeditor import CKEditorField
from wtforms.validators import DataRequired, URL


class ProjectForm(FlaskForm):
    title = StringField("Project Name",
                        validators=[DataRequired()],
                        render_kw={
                            "placeholder": "Projects Title..."}
                        )
    subtitle = StringField("Subtitle",
                           validators=[DataRequired()],
                           render_kw={
                               "placeholder": "Subtitle..."}
                           )
    img_url = StringField("Image",
                          validators=[DataRequired(), URL()],
                          render_kw={
                              "placeholder": "Image URL..."}
                          )
    body = CKEditorField("Content", validators=[DataRequired()],
                         render_kw={"placeholder": "Details..."})
    submit = SubmitField("Create Project.")

views/admin.py
from flask import Blueprint, request, session, redirect, url_for, flash, render_template
from forms import AdminForm
from controller.utils import admin_only
from werkzeug.security import generate_password_hash

from dotenv import load_dotenv
import os

load_dotenv()


admin = Blueprint("admin", __name__,
                  template_folder="../templates", static_folder="../static")


@admin.route("/admin", methods=["GET", "POST"])
def admin_login():
    form = AdminForm()
    if request.method == "POST":
        username = request.form.get("username")
        password = request.form.get("password")
        if username == os.getenv("USERNAME") and password == os.getenv("PASSWORD"):
            session["username"] = username
            session["password"] = generate_password_hash(password)
            session["is_active"] = True
            return redirect(url_for("home.index"))
        else:
            flash("Incorrect username or password.")
            return redirect(url_for("home.index"))
    return render_template("admin-login.html", form=form)


@admin.route("/logout-admin")
@admin_only
def logout():
    [session.pop(key) for key in list(session.keys()) if key != '_flashes']
    return redirect(url_for("home.index"))

views/home.py
from flask import Blueprint, request, session, render_template, send_file
from models import Service, Project
from forms import ContactForm
from controller.utils import send_message

home = Blueprint("home", __name__, template_folder="../templates",
                 static_folder="../static")

service_db = Service("services")
project_db = Project("projects")


@home.route('/', methods=["GET", "POST"])
def index():
    form = ContactForm()
    is_active = session.get("is_active", False)
    projects = project_db.get_projects()
    services = service_db.get_services()
    if form.validate_on_submit():
        send_message(request.form.get("name"),
                     request.form.get("email"),
                     request.form.get("subject"),
                     request.form.get("text")
                     )
        return render_template("index.html", form=form)
    else:
        return render_template('index.html', form=form,
                               projects=projects,
                               services=services,
                               is_active=is_active)



@home.route("/download-resume")
def download():
    return send_file("./resume.pdf", as_attachment=True)

views/project.py
from flask import Blueprint, redirect, render_template, url_for, request, session
from controller.utils import admin_only
from forms import ProjectForm, CommentForm
from models import Project

project = Blueprint("project", __name__,
                    template_folder="../templates", static_folder="../static")

db = Project(collection="projects")


@project.route("/add-project", methods=["GET", "POST"])
@admin_only
def create_project():
    form = ProjectForm()
    if request.method == "POST":
        db.add_project(form.title.data,
                          form.subtitle.data,
                          form.img_url.data,
                          form.body.data)
        return redirect(url_for("home.index"))
    else:
        return render_template("add-project.html", form=form)


@project.route("/project/<id>", methods=["GET", "POST"])
def show_project(id):
    form = CommentForm()
    comments = db.get_comments(id)

    is_active = session.get("is_active", False)
    projectID = id
    if request.method == "POST":
        db.add_comment(id,
                          form.text.data,
                          form.name.data
                          )
        return redirect(url_for("project.show_project", id=id))
    else:
        return render_template("project.html", **db.get_project(id),
                               form=form,
                               comments=comments,
                               id=projectID,
                               is_active=is_active
                               )


@project.route("/delete-project/<id>")
@admin_only
def delete_project(id):
    db.delete_project(id)
    return redirect(url_for("home.index"))


@project.route("/edit-project/<id>", methods=["GET", "POST"])
@admin_only
def edit_project(id):
    is_edit = True
    project = db.get_project(id)
    if request.method == "POST":
        db.update_project(id,
                             request.form.get("title"),
                             request.form.get("subtitle"),
                             request.form.get("img_url"),
                             request.form.get("body")
                             )
        return redirect(url_for("home.index"))
    else:
        edit_form = ProjectForm(
            title=project.get("title"),
            subtitle=project.get("subtitle"),
            img_url=project.get("img_url"),
        )
        article_body = project.get("body")  # CKeditor
        return render_template("add-project.html", form=edit_form,  article_body=article_body, is_edit=is_edit)


@project.route("/delete-comment", methods=["GET", "POST"])
@admin_only
def delete_comment():
    id = request.form.get("projectID")
    comment = [request.args.get("text"),
               request.args.get("author"),
               request.args.get("date")]
    db.delete_comment(id, comment)
    return redirect(url_for("project.show_project", id=id))


@project.route("/delete-comments", methods=["GET", "POST"])
@admin_only
def delete_all_comments():
    id = request.form.get("projectID")
    db.delete_comments(id)
    return redirect(url_for("project.show_project", id=id))

views/service.py
from flask import Blueprint, render_template, request, redirect, url_for
from forms import ServiceForm
from models import Service
from controller.utils import admin_only


service = Blueprint("service", __name__,
                    template_folder="../templates", static_folder="../static")

db = Service(collection="services")


@service.route("/add-service", methods=["GET", "POST"])
@admin_only
def add_service():
    form = ServiceForm()
    if form.validate_on_submit():
        db.add_service(form.title.data,
                       form.description.data,
                       form.img_url.data)
        return redirect(url_for('home.index'))
    return render_template("add-service.html", form=form)


@service.route("/edit-service/<id>", methods=["GET", "POST"])
@admin_only
def edit_service(id):
    is_edit = True
    service = db.get_service(id)
    if request.method == "POST":
        db.update_service(id,
                          request.form.get("title"),
                          request.form.get("description"),
                          request.form.get("img_url")
                          )
        return redirect(url_for("home.index"))
    else:
        edit_form = ServiceForm(
                                title=service["title"],
                                description=service["description"],
                                img_url=service["img_url"]
                                )
        return render_template("add-service.html", form=edit_form, is_edit=is_edit)



@service.route("/delete-service/<id>", methods=["GET", "POST"])
@admin_only
def delete_service(id):
    db.delete_service(id)
    return redirect(url_for("home.index"))


"""sumary_line
Python Geliştirme

Python günümüzün en popüler dillerinden olup nesne yönelimli, yüksek seviye bir programlama dilidir.
Veri analizinden web uygulamalarına kadar bir çok alanda performansı oldukça iyi olan python programlama dilinde kendini geliştiren biri olarak
 fikirlerinizi veya hayallerinizi dijital dünya da kodlara dönüştürmeniz de size yardımcı olabilirim. 
"""

templates/add-project.html
{% include "header.html" %}
<section class="home" id="home" style="background-image: url(../static/img/shoe.png);">
    <div class="home-text">
      {% if not is_edit %}
      <h1>
        Create New Project
      </h1>
      <h2>
        Show Your Skills To Everyone..
      </h2>
      {% else %}
      <h1>
        Edit Project
      </h1>
      {% endif %}
    </div>
  </section>
  {% if not is_edit %}
  <section class="proje">
    <div class="contact-form">
      <!-- {{ ckeditor.create(value=article_body) }} -->
      <form action="" method="post">
        {{ form.csrf_token }}
        {{ form.title.label(class_="label") }}
        {{ form.title(required='required') }}
        {{ form.subtitle.label(class_="label") }}
        {{ form.subtitle(required='required') }}
        {{ form.img_url.label(class_="label") }}
        {{ form.img_url(required='required') }}
        {{ form.body.label(class_="label") }}
        {{ form.body(required='required') }}
        
        {{ form.submit(class_="send")}}

      </form>
      {{ ckeditor.load() }}
        {{ ckeditor.config(name='body') }}
    </div>
  </section>
  {% else %}
  <section class="proje">
    <div class="contact-form">
      
      <form action="" method="post">
        {{ form.csrf_token }}
        {{ form.title(required='required') }}
        {{ form.subtitle(required='required') }}
        {{ form.img_url(required='required') }}
        {{ ckeditor.create(value=article_body, name='body') }} 
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='body') }}
        {{ form.submit(class_="send", value="Edit")}}

      </form>
    
    </div>
  </section>
  {% endif %}
  
 

{% include "footer.html" %}

templates/add-service.html
{% include "header.html" %}
<section class="home" id="home" style="background-image: url(../static/img/shoe.png);">
    <div class="home-text">
      {% if not is_edit %}
      <h1>
        Create New Service
      </h1>
      <h2>
        We know there is no limit to what you can do, but write some of them here
      </h2>
      {% else %}
      <h1>
        Edit Service
      </h1>
      {% endif %}
    </div>
  </section>
  {% if not is_edit %}
  <section class="proje">
    <div class="contact-form">
      <form action="" method="post">
        {{ form.csrf_token }}
        {{ form.title.label(class_="label") }}
        {{ form.title(required='required') }}
        {{ form.description.label(class_="label") }}
        {{ form.description(required='required') }}
        {{ form.img_url.label(class_="label") }}
        {{ form.img_url(required='required') }}      
        {{ form.submit(class_="send")}}

      </form>
    </div>
  </section>
  {% else %}
  <section class="proje">
    <div class="contact-form">
      
      <form action="" method="post">
        {{ form.csrf_token }}
        {{ form.title.label(class_="label") }}
        {{ form.title(required='required') }}
        {{ form.description.label(class_="label") }}
        {{ form.description(required='required') }}
        {{ form.img_url.label(class_="label") }}
        {{ form.img_url(required='required') }}      
        {{ form.submit(class_="send")}}


      </form>
    
    </div>
  </section>
  {% endif %}
  
 

{% include "footer.html" %}

templates/admin-login.html
{% include "header.html" %}
<section class="error" id="error">
    <div class="home-text" style="width: 100%; height:100%; margin-top:10%;">
   
      {% with messages = get_flashed_messages() %}  
      {% if messages %}  
            {% for message in messages %}  
                 <h2 style="color: #eb4a4a;">{{ message }}</h2>  
            {% endfor %}  
      {% endif %}  
   {% endwith %}  
        <div class="contact-form">
            <form action="{{ url_for('admin.admin_login') }}" method="post">
              {{ form.csrf_token }}
             <h2> {{ form.username.label }}</h2>    
              {{ form.username }}
              <h2>   {{ form.password.label }}</h2>
              {{ form.password }}
              {{ form.submit(class_="send")}}
            </form>
          </div>
     
      <div class="backhome">
      <h2 style="font-size: 3rem; letter-spacing:7px;">
       <a href="{{ url_for('home.index') }}" id="backhome">Back Home !</a> 
      </h2>
    </div>
    </div>
  </section>
</body>
  </html>

templates/footer.html
  <div class="contact-icons">
    <a href="https://www.linkedin.com/in/erkamesen/"><i class="bx bxl-linkedin"></i></a>
    <a href="https://www.facebook.com/erkam.esen.7/"><i class="bx bxl-facebook"></i></a>
    <a href="https://www.behance.net/"><i class="bx bxl-github"></i></a>
    <a href="https://www.instagram.com/erkamesenn/"><i class="bx bxl-instagram"></i></a>
    <a href="https://twitter.com/erkam_esen"><i class="bx bxl-twitter"></i></a>
  </div>
  <div class="last-text">
    <p>© Copyright - Erkam Esen {{ year }}</p>
  </div>

  <!---scroll-top--->
  <a href="#" class="top"><i class="bx bx-up-arrow-alt"></i></a>
  <a href="#contact" class="bottom"><i class="bx bx-down-arrow-alt"></i></a>
  <script src="https://unpkg.com/scrollreveal"></script>

  <!---custom js link--->
  <script type="text/javascript" src="{{ url_for('static', filename='js/script.js')}}"></script>
</body>

</html>

templates/header.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Erkam Esen</title>
  <!---custom css link--->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css')}}" />

  <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css" />

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap"
    rel="stylesheet" />
</head>

<body>
  <!---header--->
  <header>
    
    <div class="bx bx-menu" id="menu-icon"></div>

    <ul class="navbar">
      <li><a href="http://127.0.0.1:5000/#home">Home</a></li>
      <li><a href="http://127.0.0.1:5000/#about">About</a></li>
      <li><a href="http://127.0.0.1:5000/#services">Services</a></li>
      <li><a href="http://127.0.0.1:5000/#portfolio">Projects</a></li>
      <li><a href="http://127.0.0.1:5000/#contact">Contacts</a></li>
      {% if is_active  %}
      <li><a href="{{ url_for('admin.logout')}}">Logout</a></li>
      <li><a href="{{ url_for('project.create_project')}}">Add Project</a></li>
      <li><a href="{{ url_for('service.add_service')}}">Add Service</a></li>
      {%  endif  %}
      
    </ul>
  </header>

templates/index.html
{% include "header.html" %}
  <!---home--->
  <Section class="home" id="home">
    <div class="home-text">
      <h3 id="merhaba">Hello;</h3>
      <h1>
        <span>I'm </span> <span class="erkam" id="ex">A</span><span class="ra">g</span><span
          class="erkam">a</span><br />
        <span>Nabozny</span>
      </h1>
      <h3 id="alan">Shoe Designer</h3>
      <div class="contact-form">
      <form action="{{ url_for('home.download')}}" method="get">
        <input type="submit" value="Download Resume" style="width: 50%;">
      </form>
    </div>
    </div>
  </section>

  <!---about--->
  <section class="about" id="about">
    <div class="about-img">
      <img src="{{ url_for('static', filename='img/agunia.jpeg')}}" alt="Profile Pictures" />
    </div>

    <div class="about-text">
      <h2>About me</h2>
      <h4>
        Hello, I m Aga. <br>

      </h4>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed est eros, vulputate eget sodales nec, malesuada vel ante. Quisque volutpat risus in dolor sollicitudin a commodo libero suscipit. Nunc ultrices risus ut arcu hendrerit aliquet. Integer sit amet eros eu augue porttitor dictum. Quisque vel ante est, at lacinia tortor. Curabitur lacus purus, malesuada sit amet dapibus ac, placerat id leo. Nullam vel ultrices augue. Donec posuere convallis purus, sit amet imperdiet leo laoreet at. Quisque aliquam,
         urna non interdum lobortis, leo diam tincidunt lectus, non ultricies quam purus eget quam. <br> Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          Sed est eros, vulputate eget sodales nec, malesuada vel ante. Quisque volutpat risus in dolor sollicitudin a commodo libero suscipit. Nunc ultrices risus ut arcu hendrerit aliquet. Integer sit amet eros eu augue porttitor dictum. Quisque vel ante est, at lacinia tortor. Curabitur lacus purus, malesuada sit amet dapibus ac, placerat id leo. Nullam vel ultrices augue. Donec posuere convallis purus, sit amet imperdiet leo laoreet at. Quisque aliquam, urna non interdum lobortis,
          leo diam tincidunt lectus, non ultricies quam purus eget quam.

      </p>
      <hr style="color:#eb4a4a" ><br>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed est eros, vulputate eget sodales nec, malesuada vel ante.
         Quisque volutpat risus in dolor sollicitudin a commodo libero suscipit. Nunc ultrices risus ut arcu hendrerit aliquet.
          Integer sit amet eros eu augue porttitor dictum. Quisque vel ante est, at lacinia tortor. Curabitur lacus purus, malesuada sit amet dapibus ac,
           placerat id leo. Nullam vel ultrices augue. Donec posuere convallis purus, sit amet imperdiet leo laoreet at. Quisque aliquam,
         urna non interdum lobortis, leo diam tincidunt lectus, non ultricies quam purus eget quam.</p>
  </section>
  <!---services--->
  <section class="services" id="services">
    <div class="main-text">
      <h2>Services</h2>
      <h4>The bridge between ideas and physical product.</h4>
    </div>

    <div class="services-content">
      {% for service in services %}
          
     
      
      <div class="box">
        <img src="{{ service.get('img_url') }}" />
        <h3>{{ service.get('title') }}</h3>
        <p>
          {{ service.get('description') }}
        </p>
        {%  if is_active  %}
          <div class="row-icon">
              <a href="{{ url_for('service.delete_service', id=service.get('_id'))}}">Sil</a>
          </div>
          <div class="row-icon">
            <a href="{{ url_for('service.edit_service', id=service.get('_id'))}}">Edit</a>
        </div>
        {% endif %}
      </div>

      {% endfor %}

 
    </div>
  </section>

  <!---portfolio--->
  <section class="portfolio" id="portfolio">
    <div class="main-text">
      <h2>Projects</h2>
      <h4>Some of my projects</h4>
    </div>

    <div class="portfolio-content">
      {% for project in projects %}
      <div class="row">
        <a href="{{ url_for('project.show_project', id=project.get('_id')) }}">
          <img src="{{ project.get('img_url') }}"/>
        </a>
        <div class="main-row">
          <div class="row-text">
            <h6>{{ project.get("title")}}</h6>
          </div>
          {%  if is_active  %}
          <div class="row-icon">
              <a href="{{ url_for('project.delete_project', id=project.get('_id'))}}">Sil</a>
          </div>
          <div class="row-icon">
            <a href="{{ url_for('project.edit_project', id=project.get('_id'))}}">Edit</a>
        </div>
        {% endif %}
        </div>
        <h3>{{ project.get("subtitle")}}</h3>
      </div>
      {% endfor %}
    </div>
  </section>
 
  <!---contact--->
  <section class="contact" id="contact">
    <div class="contact-text">
      <h2>Contact</h2>
      <h4 style="color:#019bc6;">Strength comes from unity</h4>
      <p>
        You can contact me for cooperation or questions.
      </p>
      <div class="contact-list">
        <li>Turkey - Karabük/Safranbolu</li>
        <li>erkamesen789@gmail.com</li>
        <li>0123012301</li>
      </div>
    </div>

    <!-- FORM -->
    <div class="contact-form">
      <form action="" method="post">
        {{ form.csrf_token }}
        {{ form.name }}
        {{ form.email }}
        {{ form.subject }}
        {{ form.text }}
        {{ form.submit(class_="send")}}
      </form>
    </div>
  </section>
{% include "footer.html" %}


        <!-- DURUMA GÖRE HTML FORM -->
        <!-- <input type="text" name="name" placeholder="İsminizi giriniz..." required />
        <input type="email" name="mail" placeholder="Mail adresinizi yazınız..." required />
        <input type="text" name="title" placeholder="Konu başlığını giriniz..." required /> 
        <textarea name="mesaj" cols="40" rows="10" placeholder="Mesajınızı buraya yazınız..." required></textarea>
        <input type="submit" value="Gönder" class="send" id="buton"/> -->


        <!-- "Back-End Developer" odaklı bir yazılım geliştiricisi olarak, veri yapıları ve algoritmalar konusunda bir
        temele sahibim ve programlama dili olarak Python'da uzamanlaşmak için çalışıyorum. Çeşitli teknolojiler hakkında
        sağlam bir anlayışa sahibim; Postgresql ve MongoDB gibi veritabanlarının yanı sıra Redis gibi bellek içi veri
        depolarına da hakimim. <br> Bir Web Developer olarak HTML, CSS, JavaScript ve Flask Framework hakkında bilgi sahibiyim. Her
        zaman becerilerimi ve bilgilerimi yeni zorluklara uygulamanın ve bir geliştirici olarak öğrenmeye ve büyümeye
        devam etmenin yollarını arıyorum. Öğrenme yeteneğim güçlüdür, yeni teknolojilere kolayca uyum sağlayabilirim.
        Kodlamayı ve özellikle öğrendiklerim ile üretmeyi çok seven bir insanım. -->

templates/project.html
{% include "header.html" %}
<section class="home" id="home" style="background-image: url(../static/img/shoes2.png);">
    <div class="home-text">

      <h1>
        {{ title }}
      </h1>
      <h2>
        {{ subtitle }}
      </h2>
    </div>
    
  </section>
  
  <section class="project">
    <div class="project" id="project">
      <h2>{{ title }}</h2> <br>
      <h3> 
        {{ subtitle }}
      </h3> <br>
      <p style="list-style: circle;">
      {{ body|safe }}  <!-- HTML decode için kullanıyoruz eğer kullanmazsak tagleri yazıyor. -->
    </p>
  </section>
  
  <section id="commentSection">
    {% if is_active  %}
    <form action="{{ url_for('project.delete_all_comments')}}" method="post">
      <input type="text" hidden name="projectID" value="{{ id }}">
      <button class="home-text" >Delete All Comments</button>
    </form>
    {%  endif  %}
    <hr style="color:#eb4a4a" ><br>
    {% for comment in comments %}
        
    <ol class="commentlist" id="commentlist">
    <div class="comment-wrap" id="comment-1765770">
      <div class="comment-author-wrap">
        <div class="comment-author">{{ comment.get("author")|e }}</div>
        <div class="commenterImage">
          <img src="{{ comment.get('author')|gravatar }}"/> <!-- GRAVATAR -->
      </div>
         <div class="comment-time">{{ comment.get("date")|e }}</div>
         {% if is_active  %}
         <div class="home-text">
            <form action="{{ url_for('project.delete_comment', text=comment.get('text') ,author=comment.get('author'),date=comment.get('date')) }}" method="post">
              <input type="text" hidden name="projectID" value="{{ id }}">
              <button class="home-text" >X</button>
            </form>
         </div>
         {%  endif  %}
      </div>   
      <div class="comment-content">
        <p>{{ comment.get("text")|e }}</p>
      </div>
    </ol>
    <hr style="color:#7f7e6b;width:20%;text-align:center;" ><br>
    {% endfor %}
  </section>
  <section class="make-comment">
    <h1 style="text-align: center;margin-bottom:10px;">Comments</h1>
    <div class="contact-form">
      <form action="" method="post">
        {{ form.csrf_token }}
        {{ form.name }}
        {{ form.text }}
        {{ form.submit(class_="send")}}
      </form>
    </div>
  </section>

{% include "footer.html" %}
<!-- comment={'author':comment.get('author'),
                                                'date':comment.get('date'), 'text':comment.get('text')})}} -->